### ISSUE TITLE
GitHub action runner OS not set

### ISSUE THREAD

**Issue by WSDeWitt** [matsengrp/gctree#114]
The matrix for this build/test workflow specifies ubuntu and macos, but the first line hard codes the runner to be ubuntu.
https://github.com/matsengrp/gctree/blob/37792e03321558cfbc175741c485e45fc828154c/.github/workflows/build-and-test.yml#L12-L16
I think we want to replace to something like:
```yml
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
```
